### ISSUE TITLE
Response time tests not run correctly?

### ISSUE THREAD

**Issue by edisonchan** [andymanic/OSRTT#6]
**What topic does your question cover? (ie end-user usage, C# code, C code, hardware)**
end-user usage.

**What's-up, doc?**
The OSRTT attched like below: 
![IMG_20230228_192515](https://user-images.githubusercontent.com/8596506/221844206-585bb473-b735-4711-a21c-c891e9444ff3.jpg)

I received OSRTT yesterday and tested it on the AOC PD32M. The response time test seems to have failed to execute correctly. After clicking the response time test, a blank window will pop up, and there is no press key prompt on the OSRTT screen (if it is input delay test mode, it will prompt Press the button at the top).

After waiting for about two hours, the blank window is still there. Press ESC or Alt+F4 to close the blank window. You can see that the progress bar of OSRTT Launcher is running and then disappears quickly. Click to enter the test result folder, and the generated AOC PD32M The test results directory is empty and no result files are generated.

OS: Windows 11 fresh install
OSRTT Launcher version: 4.0
Windows screen scale mode: 100%.
GPU: NVIDIA RTX 3060(driver : 528.xx)

**Comment by andymanic** [comment]
You do need to use the button to start any test - although I'll add a prompt to the firmware for the response time test to make that clear.

With that said, the PD32M is a Mini LED display that I don't think will work well with OSRTT. Give it a try anyway, but you might want to use the live view mode to see what I mean. It's backlight is PWM controlled at quite a low frequency (~500Hz if I remember correctly) which means the display won't output light while the backlight is off. 

Closing the issue here.

**Comment by edisonchan** [comment]
The OSRTT Pro show BACKLIGHT STROBING TEST CANCELLED after I pressed the button.

**Comment by andymanic** [comment]
![image](https://user-images.githubusercontent.com/7023048/222107955-c14b838f-883f-4e77-b15e-d4eb2fcdb9d7.png)
The Dell seems to be very slow on input latency, so the transition isn't being captured. Set the capture time to 200ms and it should work
